name: PR build

on: [pull_request_target]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_STDLIB_TOKEN }}
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.BALLERINA_STDLIB_TOKEN }}
        run: |
          set -e
          ./gradlew clean build codeCoverageReport --stacktrace --scan --console=plain --no-daemon
